package com.example.social.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    POST_NOT_FOUND,
    COMMENT_NOT_FOUND,
    AUTH_PHONE_INVALID,
    AUTH_PHONE_ALREADY_REGISTERED,
    AUTH_VERIFICATION_NOT_FOUND,
    AUTH_OTP_INVALID,
    AUTH_OTP_EXPIRED,
    AUTH_OTP_ATTEMPTS_EXCEEDED,
    AUTH_REGISTRATION_TOKEN_INVALID,
    AUTH_CREDENTIALS_INVALID,
    AUTH_REFRESH_TOKEN_MISSING,
    AUTH_REFRESH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_REUSE_DETECTED,
    AUTH_UNAUTHORIZED,
    AUTH_TWILIO_UNAVAILABLE,
    UPLOAD_INVALID_FILE,
    UPLOAD_TOO_LARGE,
    UPLOAD_STORAGE_UNAVAILABLE
}
